INSERT INTO products (canonical_name, product_type) VALUES
('Herbal Hair Color', 'SINGLE'),
('Thaazhai Rosemary Hydrosol', 'SINGLE'),
('Thaazhai Herbal Conditioning Shampoo', 'SINGLE'),
('Thaazhai Aloe Vera Premium Natural Moisturizing Gel', 'SINGLE'),
('Thaazhai Complete Hair Care Combo 1', 'COMBO'),
('Thaazhai Rose Hydrosol', 'SINGLE'),
('Hair Growth Serum', 'SINGLE'),
('Herbal Glow Face Wash', 'SINGLE'),
('Thaazhai Complete Hair Care Combo 2', 'COMBO'),
('Thaazhai Aloevera Gel and Hair colour', 'COMBO'),
('Manjistha & Licorice Radiance Soap', 'SINGLE'),
('Thaazhai Hair Strengthening Duo', 'COMBO'),
('A2 Ghee Lip Balm', 'SINGLE'),
('Glow Booster Skin Serum', 'SINGLE'),
('Rose & Vetiver Body Wash', 'SINGLE'),
('Elladi Ayurvedic Radiance Day Cream', 'SINGLE'),
('Rose Hydrosol & Aloe Vera Gel Combo', 'COMBO'),
('Anti-Frizz Gold Hair Serum', 'SINGLE'),
('ABC Radiance Soap – Apple • Beetroot • Carrot', 'SINGLE'),
('Thaazhai Hair Serum', 'SINGLE'),
('Tejas Night Cream', 'SINGLE'),
('2-in-1 Hair Mask & Conditioner', 'SINGLE')
ON CONFLICT (canonical_name) DO NOTHING;
